pipelines:
  - name: Linux_Dont_Upload_Run_State_Archice
    steps:
      - name: S_Bash_Util_0005_1
        type: Bash
        execution:
          onExecute:
            - touch file.txt
            - echo "Hello frog" >> file.txt
            - add_run_files file.txt jfrog_pipeline

      - name: S_Bash_Util_0005_2
        type: Bash
        configuration:
          inputSteps:
            - name:  S_Bash_Util_0005_1
        execution:
          onExecute:
            - restore_run_files jfrog_pipeline $step_tmp_dir
            - ls -la jfrog_pipeline

  - name: Linux_Upload_Run_State_Archice
    steps:
      - name: S_Bash_Util_0005_1
        type: Bash
        configuration:
          environmentVariables:
            JFROG_PIPELINES_RUN_STATE_DEBUG: 'true'
        execution:
          onExecute:
            - touch file.txt
            - echo "Hello frog" >> file.txt
            - add_run_files file.txt jfrog_pipeline

      - name: S_Bash_Util_0005_2
        type: Bash
        configuration:
          inputSteps:
            - name:  S_Bash_Util_0005_1
          environmentVariables:
            JFROG_PIPELINES_RUN_STATE_DEBUG: 'true'
        execution:
          onExecute:
            - restore_run_files jfrog_pipeline $step_tmp_dir
            - ls -la jfrog_pipeline

  - name: Powershell_Dont_Upload_Run_State_Archice
    configuration:
      nodePool: win_2019
    steps:
      - name: S_PS_UTIL_6380_006_1
        type: PowerShell
        execution:
          onExecute:
            - Set-Content -Path "test_file" -Value ${run_id}
            - add_run_files test_file test_file
      - name: S_PS_UTIL_6380_006_2
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_PS_UTIL_6380_006_1
        execution:
          onExecute:
            - restore_run_files test_file test_file
            - restore_run_files test_file test_file2


  - name: Powershell_Upload_Run_State_Archice
    configuration:
      nodePool: win_2019
    steps:
      - name: S_PS_UTIL_6380_006_1
        type: PowerShell
        configuration:
          environmentVariables:
            JFROG_PIPELINES_RUN_STATE_DEBUG: 'true'
        execution:
          onExecute:
            - Set-Content -Path "test_file" -Value ${run_id}
            - add_run_files test_file test_file
      - name: S_PS_UTIL_6380_006_2
        type: PowerShell
        configuration:
          inputSteps:
            - name: S_PS_UTIL_6380_006_1
          environmentVariables:
            JFROG_PIPELINES_RUN_STATE_DEBUG: 'true'
        execution:
          onExecute:
            - restore_run_files test_file test_file
            - restore_run_files test_file test_file2
