pipelines:
  - name: mytest_success
    steps:
      - name: step1
        type: Bash
        execution:
          onStart:
            - end_step success
            - echo "onStart command"
  - name: mytest_failure
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - end_step failure
            - echo "onStart command"

  - name: mytest_skipped
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - end_step skipped
            - echo "onStart command"

  - name: mytest_onfailure_failed
    steps:
      - name: step1
        type: Bash
        execution:
          onExecute:
            - echo "onExecute command"
            - end_step failure
          onFailure:
            - end_step skipped
